### ISSUE TITLE
grid would be awesome

### ISSUE THREAD

**Issue by caspahouzer** [macCesar/tailwind-tss-color-generator#4]
maybe you got it done to get https://tailwindcss.com/docs/grid-template-columns working for tss

**Comment by macCesar** [comment]
Hi there!!! 

I will look into it!!

**Comment by caspahouzer** [comment]
I made a workaround for grid using w-1/2 and do the right/left thing with modulo 2 :-D

But a real grid would be great

![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2020-05-26 at 21 05 55](https://user-images.githubusercontent.com/1126641/82940163-b5a9c600-9f94-11ea-9622-5611423e13c0.png)

**Comment by macCesar** [comment]
I think that's the only way to 'simulate' a grid system in Appcelerator.

Views in Appcelerator don't have a way to force their children to shrink their width or height to fit them.

I have a standalone helper ( not related to tailwind.tss ) to calculate the necessary width ( and margin ) of a child according to the number of elements in a row.
