### ISSUE TITLE
Design issues with SDK 9.1.0.GA

### ISSUE THREAD

**Issue by caspahouzer** [macCesar/tailwind-tss-color-generator#8]
Today the GA version of SDK 9.1.0 was released. After first compile, my app looks like this.

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-26 at 08 32 31](https://user-images.githubusercontent.com/1126641/91269053-b3fbc400-e776-11ea-847e-c737f8953c3f.png)

Compiling with a previous SDK version e.g. 9.1.0.v20200814072027 works right as you can see.

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-26 at 08 34 24](https://user-images.githubusercontent.com/1126641/91269178-f6250580-e776-11ea-9ec0-dca5c6b871cc.png)

Any idea what could be wrong here and what I could do?

**Comment by caspahouzer** [comment]
It’s not related to you. There’s an issue on the sdk side

https://jira.appcelerator.org/plugins/servlet/mobile#issue/TIMOB-28101

**Comment by macCesar** [comment]
Hi @caspahouzer, 

Sorry for the late response, I've been very busy with extra work!!

I'll keep an eye on that ticket!!!

**BTW, have you seen my other project called [purgeTSS](https://github.com/macCesar/purgeTSS)?**

You will find it easier to work with it!

**Especially to keep the file size of all compiled styles as small as possible!!!**

As much as I'd like to keep both projects in sync. In the future, I'm going to ditch `tailwind-tss-color-generator`.

With `purgeTSS` once you install it globally, you just:

1. Create a new project.
2. Start using any of the supported [tailwind.tss](https://github.com/macCesar/purgeTSS/blob/master/tss/tailwind.tss) styles ( and [fontawesome.tss](https://github.com/macCesar/purgeTSS/blob/master/tss/fontawesome.tss) styles for that matter ).
3. Run `purgetss` before compiling

**And that's it!!!**

**You will get a slim `app.tss` file with just the classes used in your Views.**

If you are going to use FontAwesome Fonts in your project you just run `purgetss fonts` once; and it will copy the necessary fonts into `assets/fonts/`

I'm planning to include [Material design icons](https://github.com/google/material-design-icons)

And maybe [Heroicons](https://github.com/tailwindlabs/heroicons) although I haven't found a GOOD SVG-to-Font converter!!!
